name: hub-action test
on: [push]

jobs:
  cypress-run:
    name: hub-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.13.0-chrome78-ff70
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
      - name: Store Cypress Video Artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test-e2e-cypress-videos
          path: test/e2e/videos
